---
title: "Master Thesis"
subtitle: "Economics of Sustainability and the Environment"
author: "Felix Schulz"
format:
  pdf:
    toc: false
    number-sections: true
    link-citations: true
bibliography: "./Environmental Economics Project.bib"
---

# Introduction

The rainforests of the Amazon are under severe pressure from deforestation. In the two centuries leading up to 2022, 8.6% of primary forests in Brazil were cleared [@worldresourcesinstituteGlobalForestWatch2023]. The importance of these areas is manifold. Their extreme levels of biodiversity have high intrinsic value to the world's ecosystem  [@maslinNewViewsOld2005; @laurila-pantHowValueBiodiversity2015] and local communities [@omettoAmazonDeforestationBrazil2011]. Land use change in primary forests releases large amounts of greenhouse gases, which in turn have negative impacts on a global scale [@malhiClimateChangeDeforestation2008; @harrisGlobalMapsTwentyfirst2021]. As a carbon sink, rainforests bind greenhouse gas, working against climate change [@harrisGlobalMapsTwentyfirst2021]. Logging has lead to an estimated emission of around 36 gigatonnes of CO2-equivalent greenhouse gas emissions from 2001 to 2022 in Brazil alone [@worldresourcesinstituteGlobalForestWatch2023]. 

Economists model deforestation decisions as a tradeoff between its cost and benefits. We observe that cleared land is reused for agriculture, lifestock or mining [@baronaRolePastureSoybean2010; @sonterMiningDrivesExtensive2017]. These endeavors of alternative use are profitable for their owner but occur costs reaching far beyond the limits of the given areas. Based on the discussed negative impacts on climate change alone, researchers conclude that the social costs through climate change would, if considered by the market, render all agricultural conversion in the Amazon inefficient [@souza-rodriguesDeforestationAmazonUnified2019].

In addition to the global reaching effects of deforestation on the climate, there is a substantial body of literature discussing its impact on local utility in the form of health outcomes. Empirical evidence from medical and geoscientific research find negative effects of deforestation-related wildfires and on malaria prevalence [see for example @reddingtonAirQualityHuman2015; @tuckerlimaDoesDeforestationPromote2017]. Given the existing evidence it appears likely that these dangers to the local communities are not considered to the extent it would be socially desireable [@NBERw31410].

In the research proposed in this essay I seek to shed a light on the importance of rivers in propagating pollution of deforestation on a vast geographical scale. In other words, I want to find evidence of the role of rivers on health outcomes when there occurs deforestation upstream. I seek to test the hypothesis that deforestation leads to river pollution, impacting areas far from the actual forest in question. Previous work has shown the important role of forests in preventing soil erosion [see for example @wilkinsonPresentSoilErosion1994; @veldkampDeforestationReforestationImpacts2020]. Absent this, one would expect increased river pollution downstream of areas subject to logging. Agricultural land use of cleared land may further increase this effect through livestock-related ground pollution [@montgomerySoilErosionAgricultural2007]. If these concerns turn out substantiated, I will be able to uncover a potentially far-reaching fallout beyond the scope of our current understanding of deforestation's effects.

The impact of deforestation on health outcomes has been subject of several publications [@ellwangerDiversityLossClimate2020; @reddingtonAirQualityHuman2015]. The costs of soil erosion were also discussed in a broad range of literature [see for example @tellesCostsSoilErosion2011]. @NBERw31410 provide an excellent review on the economics of deforestation. Soil erosion as a driver of pollution and pollution-induced health costs has to the best of knowledge only been covered in a small-scale fashion by @maHumanHealthRisk2014 and therefore remains a gap in the research. 

The remainder of this proposal is structured as follows: In the next section I review literature on the economics of deforestation and outline the existing policy framework to establish the importance of the study at hand. I then further introduce the mechanism of how deforestation may impact public health through soil erosion. In the final section I give an overview on how I envision the research project to proceed.

# Literature Review

## Economic Models of Deforestation

Driven by short-run benefits of lumber or alternative land use, researchers observe unprecedented levels of rainforest degradation in the anthropocene [@malhiClimateChangeDeforestation2008]. This is of elevated importance as any loss of primary forests cannot be undone in any reasonable temporal scope [@shuklaAmazonDeforestationClimate1990; @NBERw31410]. The scientific evidence for the negative impacts of deforestation raises the concern that these externalities are not internalized by the forest extraction market and that deforestation does not occur at a socially optimal rate. At the core of this thought lies the (monetary) assessment of the societal cost of deforestation against the economical gains from alternative use and timber. 

Many economic models have been developed to weigh these benefits and external costs on a local and global scale. In their analysis, @NBERw31410 describe several such models of decision making for deforestation. Their benchmark model, which they claim to closest resemble the microeconomic process of decisionmaking today, disregards externalities but instead focuses on short-run benefits. In fact, discounting of future income leads to a situation where this benchmark model does not guarantee extraction rates that are at or below a *maximum sustained yield* of forest regrowth. They note that lack of property rights and regulation further increases discounting rates in regions like Brazil.

Extended models then acknowledge the fact that deforestation is associated with social costs that are not internal to the parties with property rights to the forest [@balboniAppendixEconomicsTropical2023]. By modeling this cost as a fixed shift to the private marginal cost, the socially optimal equilibrium lies below the market-achieved private rate. This underlines the necessity to internalize these costs through policy. Economic theory yields several instruments to achieve this goal. Pigouvian taxes on logging or subsidies for landowner to *not* remove a forest are among the popular [@NBERw31410]. I discuss several such attempts in @sec-policy. It does however remain essential to know the extent of the social costs of deforestation for any such policy to work. My proposed paper therefore has important policy implications by shedding a light on the superlocal health cost of logging across Brazil.

## Policy Instruments on Deforestation {#sec-policy}

From an ecological point of view, @malhiClimateChangeDeforestation2008 outline their much-cited recommendation on policy agendas managing deforestation in the Amazon: To avoid reaching catastrophic tipping points, a gross maximum deforestation rate of 30%-40% with limited fragmentation should be targeted. They suggest migration corridors, river conservation and the protection of a core rainforest to the end of preserving biodiversity. Finally, education initiatives should target a reduction in wildfires.

Historically, government development policy in Brazil has been a major driver of deforestation, enabling access through large-scale infrastructure projects and subsidies on lifestock and mining endeavors [@maharGovernmentPoliciesDeforestation1989]. Since 1965, the Forest Code regulates land use in the Amazon [@soares-filhoCrackingBrazilForest2014]. While changes in the 1990s have increased its focus on conservation, conflicting interest of the agricultural sector have limited its requirements and kept compliance low. 

Brazil has since made extensive pledges to reduce deforestation-related emissions and implements a range of policy and monitoring instruments to ensure attainment [@tacconiLawEnforcementDeforestation2019]. The Detection of Deforestation in Real Time (DETER) system and Action Plan for the Prevention and Control of Deforestation in the Legal Amazon (PPCDAm) of 2004 have been shown to have significantly reduced deforestation through monitoring and enforcement efforts [@nepstadSlowingAmazonDeforestation2014; @internationalpartnershiponmitigationandmrvImplementingPreventionControl2018]. 

Since its inception in 2008, the Amazon Fund is important cornerstone policy in Brazil's strategy against deforestation [@correaAmazonFund102019]. It is at its core an implementation of the principles of the Reducing Emissions from Deforestation and Forest Degradation (REDD+) framework. International donations are used to fund conservation projects in monitoring existing regulation, maintaining protected areas, supporting sustainable production and investments in innovations. The central idea is to make payments conditional on environmental efforts and thereby subsidize abatement for those who would not have been able to afford it void the transfers [@NBERw31410]. The effectiveness and efficiency of this command-and-control approach is however disputed [@correaAmazonFund102019]. *Bolsa Verde*, another example of a REDD+ program, paying poor landowners in the Amazon to maintain forest cover is considered to be cost effective [@RePEc:cgs:wpaper:110].

## Health Externalities of Deforestation {#sec-health_effects}

The body of research on impacts of deforestation on human health is manifold. There exists convincing evidence that fires used to clear forests lead to increased air pollution and levels of mortality due to pulmonary diseases [@reddingtonAirQualityHuman2015]. While the latter form of pollution may have lingering effects on health, this mechanism of impact of inherently tied to the moment of first clearing a forest. Other studies focus on latent forms of damage arising from the altered landscape after deforestation. It turns out that several species of mosquito connected to spreading Malaria thrive in the cleared areas with more open land and artificial water infrastructure [for example see @olsonDeforestationMalariaMancio2010]. There is however significant debate if this is in fact the driving mechanisms for some of the observed correlations. Increased human exposure to mosquito habitat, increased immunity and biased data on health outcomes may serve as alternative explanations [@tuckerlimaDoesDeforestationPromote2017]. 

Research has revealed how soil after deforestation features significantly altered biological properties, reducing its ability to retain nutrient storage essential for agriculture and deteriorating its function as greenhouse gas storage [@veldkampDeforestationReforestationImpacts2020]. Important for the context of this study, reduced erosion resistance is another key finding of many studies [for example see @molinaComplexLandCover2012; @zhengEffectsErosionPatterns2005; and @restrepoa.ImpactoDeforestacionErosion2015]. @veldkampDeforestationReforestationImpacts2020 review how the change in soil properties resulting from deforestation and alternative use decrease the ability of soil to allow vertical water flow, increasing the likelihood of erosion through overland flow. This effect is mediated by the type of soil, the slope of the landscape and the kind of replacing alternative use [@pimentelEnvironmentalEconomicCosts1995]. Ecological accounts of the impact of this process range from negligible [@neillWatershedResponsesAmazon2013] to devastating [@giertzAssessingEffectsLand2005]. @hohnerWildfiresAlterForest2019 describe how wildfires used for deforestation may further amplify erosion. 

This now allows me to sketch a clear story of the mechanism I want to survey following the framework of *contamination*, *exposure* and *dose-response* [for example see @graffzivinEnvironmentHealthHuman2013]. Deforestation (the independent variable of the study) impacts soil erosion, leading to river pollution (*contamination*), then drinking water pollution (*exposure*) and finally negative health outcomes (*dose-response*). Future statistical analysis may include the discussed mediating factors as controls or interaction terms. This model also allows me to potentially estimate a range of models for every stage of the framework if data is available.

While most research focuses on the on-site productivity losses caused by soil degradation, there is existing evidence on how increased erosion impacts sediment runoff and water pollution off-site. @maHumanHealthRisk2014 describe how deforestation increased toxic contamination in a Chinese region subject to deforestation-induced erosion but only indirectly estimate impacts on health outcomes. Most economic estimations of the externalities are tied to estimating defensive expenditures in water pollution. As early as 1988, @holmesOffsiteImpactSoil1988 finds that this increase in erosion leads to increased defensive water treatment cost. In a more recent study @vincentValuingWaterPurification2016 estimate that forest cover decreases water treatment expenditure in Malaysia.

Extending the context to a more wholistic view on social costs in general, in addition to the health outcomes outlined above, the social costs of soil erosion include dam silation and flooding. @clarkErodingSoilsOfffarm1985 calculated the social cost of offsite erosion at USD 3 billion to USD 13 billion in 1980 and the United States alone. @pataultAnalysisOffsiteEconomic2021 estimate the offsite cost of erosion for two sites in Northern France and find costs in the range of EUR 1,000 to EUR 4,300 per year and kilometer squared. 

I seek to add to this literature on a larger scale by observing health outcomes and deforestation alongside its mediating factors using remote-sensing data.

# Research Outline

The aim of the proposed paper is to show a connection between deforestation and downstream health impacts. Above I established a model of potential touchpoints at which health impacts may be measured or proxied for. The first step of research will be to evaluate the feasibility to obtain data. Next up the data has to be collected and descriptive statistics calculated. Finally I want to estimate (spatial) regression models to quantify the damage of deforestation-conditioned soil erosion.

## Data

My initial focus will lie on getting a comprehensive spatiotemporal panel of land cover change to observe deforestation and alternative use over time. Existing products like the Sentinel 2-derived Land Use Time Series by [Esri](https://www.arcgis.com/home/item.html?id=cfcb7609de5f478eb7666240902d4d3d) or [Copernicus](https://land.copernicus.eu/global/products/lc) may provide entry points but only go  as far back in time as 2017 and 2015 respectively. To allow for more nuanced analyses I seek to train and benchmark a range of Neural Networks and predict land cover maps for all Landsat 7 imagery since 1999. Candidate Networks are EfficientNet [@tanEfficientNetRethinkingModel2020a] and EfficientTransformer [@xuEfficientTransformerRemote2021].

A substantially harder challenge will be the acquisition of outcome indicators. Water quality measurement points across Brazil are sparse. I want to evaluate in how far machine learning may help estimate river pollution. Furthermore, there does to the best of my knowledge not exist a comprehensive database of drinking water quality. It may be possible to proxy this by expenditure on water treatment. The availability of data in this domain is however also questionable. The Brazilian government does record annual mortality statistics which I may use in addition to health surveys. The availability of geolocated survey data with sufficient variation for inference is however also uncertain.

## Methodology

If data on outcomes are successfully collected, I may then proceed to derive measurements of deforestation and alternative use and aggregate them along rivers. These variable can then be used in econometric regression models to estimate coefficients for the impact of erosion on public health. Mediating factors for the mechanism of erosion are the kind of alternative use, slope of terrain and general soil type present [@pimentelEnvironmentalEconomicCosts1995]. These may be used as interaction terms in the regressions. 

Finally, if the spatial setup and scale of analysis at hand does not already yield causal evidence, an instrumental variables strategy may be explored. @assuncaoDETERingDeforestationAmazon2023 show that enforcement of conservation laws is driven by satellite imagery. If high levels of cloud cover at a given forest site regularly prohibit remote sensing, this may impact deforestation but is potentially exogenous to any public health outcomes downstream.

## Discussion

After the statistical research has concluded I want to discuss the findings in an economic context. I want to look into possible implications on policy and provide visualization of my findings.

# Conclusion

The rainforests of the Amazon are under significant threat due to deforestation, with alarming consequences both locally and globally. While deforestation presents short-term economic benefits, it also brings with it considerable social costs, including impacts on climate change and detrimental health outcomes for local communities. 

This essay proposes a research study to delve deeper into a less explored facet of deforestation: the potential connection between deforestation and downstream health impacts due to river pollution. The underlying hypothesis is that deforestation results in soil erosion, leading to river pollution, and subsequently causing adverse health effects in areas far removed from the deforested region. Although there exists some literature on the direct health impacts of deforestation and the costs of soil erosion, the indirect, long-range health impacts via river pollution have been relatively under-researched. The proposed study aims to bridge this gap in understanding by utilizing a combination of satellite imagery and machine learning techniques to analyze the effects of deforestation on river pollution and associated health outcomes. 

Should the findings validate the hypothesis, they would underscore the broader repercussions of deforestation and emphasize the urgent need for policies that effectively internalize these external costs, thus prompting a more holistic approach to forest conservation in the Amazon and beyond.

# References {.unnumbered}

:::{#refs}
:::